<?php

namespace Panier\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LigneCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeRepository extends EntityRepository
{
}
