parameters:
#    panier_admin.example.class: Panier\AdminBundle\Example

services:
#    panier_admin.example:
#        class: %panier_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
